#!/usr/bin/env bash
# configure new ubuntu machine 
# nginx should be port 80
# serve a page that would return a hello world world string

sudo apt-get update -y -qq && \
	sudo apt-get install nginx -y

sudo service nginx start

sudo utw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/html.nginx-debian.html.bckp
echo -e "Hello World !" | dd status=none of=/var/www/html/index.nginx-debian.html

sudo service nginx restart

echo -e "\ncompleted \n"
