#!/usr/bin/env bash
# TO deplicate web-01 to web-02

echo -e "UPDATING AND DOING A FEW CHECKS...\n"

function install() {
    command -v "$1" &> /dev/null

    #shellchwck disable=SC2181
    if [$? -ne 0 ]; then
            echo -e "       Installing: $1$\n"
            sudo apt-get update -y -qq && \ sudo apt-get install -y "$1" -qq
            echo -e "\n"
    else
            echo -e "       ${1} is already installed.\n"
    fi
}

install nginx #install nginx

echo -e "\nSETTING UP A FEW MINOR THINGS.\n"

# To allow NGINX on Firewall
sudo ufw allow 'Nginx HTTP'

# To give the user ownership to website files for easy editing
if [ -d "/var/www" ]; then
        sudo chown -R "$USER":"$USER" /var/www
        sudo chmod -R 755 /var/www
else 
        sudo mkdir -p /var/www
        sudo chown -R "$USER":"$USER" /var/www
        sudo chmod -R 755 /var/www
fi

# To create dir if not exist
for dir in /var/www/{html, error}; do
        if ! [ -d "$dir" ]; then
                mkdir -p "$dir"
        fi
done

# To create new index
echo "Hello World!" > /var/www/html/index.html

# To create new error page
echo "Ceci n'est pas une page" > /var/www/html/error_404.html

# backup default server config file
sudo cp /etc/nginx/sites-enabled/default nginx-sites-enabled_default.backup

server_config=\
"server {
            listen 80 default_server;
            listen [::]:80 default_server;
            root /var/www/html;
            index index.html index.htm index.nginx-debian.html
            server_name_;
            add_header X-served-By \$hostname;
            location / {
                try_files \$uri \$uri/ =404;
            }
            if (\$request_filename ~ redirect_me) {
                rewirte ^ https://github.com/tewa92/ permanent;
            }
            error_page 404 /error_404.html
            location = /error_404.html {
                interval;
            }
}"

#shellcheck disable= SC2154
echo "$server_config" | sudo dd status=none of=/etc/nginx/sites-enabled/default

if [ "$(pgrep -c nginx)" -le 0 ]; then
        sudo service nginx start
else
        sudo service nginx restart
fi
