#!/usr/bin/env bash
# To install load balancer

echo -e "UPDATING AND DOING A FEW THINGS...\n"

ffunction install() {
    command -v "$1" &> /dev/null

    #shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
            echo -e "       Installing: $1\n"
            sudo apt-get update -y -qq && \ sudo apt-get install -y "$1" -qq
            echo -e "\n"
    else
            echo -e "       ${1} is already installed.\n"
    fi
}

install haproxy # To install haproxy

echo -e "\n SETTING UP A FEW THINGS.\n"

#BACKUP Default Server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
    mode http
    timeout client 15s
    timeout connect 10s
    timeout server 15s
    timeout http-request 10s

frontend code2me-tech-frontend
    bind *:80
    default_backend code2me-tech-backend

backend code2me-tech-backend
    balance roundrobin
    server 32781-web-01 54.90.32.100:80 check
    server 32781-web-02 35.153.194.233:80 check
"

#shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# To enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

echo "configured - Roundrobin on web-01 & web-02"

if [ "$(pgrep -c haproxy)" -le 0]; then
        sudo service haproxy start
else
        sudo service haproxy restart
fi
