#!/usr/bin/env bash
# sends 5 ping requests to the specified IP address received as an argument.
if [ $# -eq 0 ]
then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
  ping -c 5 "$1"
fi
