#!/usr/bin/env bash
# Debugging NGINX (service (init) must say that NGINX IS NOT RUNING)
sudo sed -i "s/8080/80/" /etc/nginx/sites-enabled/default
sudo service nginx restsrt
echo "" | sudo dd status=none of=/run/nginx.pid
