#!/usr/bin/env bash
# This is going to displays "To infinity and beyond" indefinitely with
#+ a sleep 2 in between each iteration.
#   This is going to displays "I am invincible!!!" in between each iteration.

while true

do

  echo "To infinity and beyond"

  sleep 2

  trap 'echo "I am invincible!!!"' SIGTERM 

done
