#!/usr/bin/env bash
# "Sets up a web server configuration to operate Nginx with the user 'nginx',
# while it listens on port 8080."
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
