#!/usr/bin/env bash
# Find the Gunicorn master process PID using pgrep
MASTER_PID=$(pgrep -f 'gunicorn.*master')

# Reload Gunicorn gracefully
if [ -n "$MASTER_PID" ]; then
  kill -HUP "$MASTER_PID"
  echo "Gunicorn reloaded gracefully."
else
  echo "Gunicorn master process not found."
fi
