#!/usr/bin/env bash
# Find the Gunicorn master process PID
MASTER_PID=$(ps aux | grep 'gunicorn' | grep 'master' | awk '{print $2}')

# Reload Gunicorn gracefully
if [ -n "$MASTER_PID" ]; then
  kill -HUP "$MASTER_PID"
  echo "Gunicorn reloaded gracefully."
else
  echo "Gunicorn master process not found."
fi
